### ISSUE TITLE
[FR] option to open separate pane in sidebar instead to adding to exitng one

### ISSUE THREAD

**Issue by danieltomasz** [lynchjames/obsidian-writing-goals#1]
Great plugin! Would be great to have possibility to open the counter in separate pane in the sidebar, not to be added at the bottom of existing ones.

**Comment by lynchjames** [comment]
Actually, I think the behaviour you're looking for and shown in the clip above should be the default as is the case for core plugins. I'll mark this as a bug and fix. Thanks.

**Comment by danieltomasz** [comment]
hi! thank you, this is behaviour is requested indeed🙂

**Comment by danieltomasz** [comment]
in the example are you adding another pane with its own icon in the right sidebar? the gif you added, the pane with the 'writing goals' does seem to replace existing one, not to add another one, but I might be missing something

**Comment by lynchjames** [comment]
It is adding a new pane with its own icon but the icon is obscured in the UI off to the right of the calendar icon. This is standard Obsidian behaviour when adding tabbed panes to the right panel.

**Comment by danieltomasz** [comment]
Yes, I was able to update the plugin and check on my computer, thank you!
