### ISSUE TITLE
[Fr] Option to set/reset minimum values of daily word count  to 0

### ISSUE THREAD

**Issue by danieltomasz** [lynchjames/obsidian-writing-goals#14]
Today after the changes in detecting comment in text my project I got into displaying -1500 words in daily progress , this could happen later as well with the removal of a large chunk of text, and it could be demotivating.

Would be great to have possibility to set minimal/reset value displayed to 0 and start adding new words starting from this value as an option in settings  (someone  still could be motived to see values <0).

**Comment by lynchjames** [comment]
True, that makes sense. I'll pick this up.

**Comment by lynchjames** [comment]
`Allow negative daily goal progress` toggle setting has been added in release 0.4.3:

`False` - If the current note or sum of folder notes word count minus the starting point of the daily goal progress for that day is less than 0, the progress will be displayed as 0 until words are added. At this point, the progress will increase from 0.

`True` - Daily goal progress will always show the current note or sum of folder notes word count minus the starting point of the daily goal progress for that day, even if the figure is negative.
