### ISSUE TITLE
[FR] Improve writing goal display scaling

### ISSUE THREAD

**Issue by FeralFlora** [lynchjames/obsidian-writing-goals#17]
The scaling of the writing goal circle and text makes it so that the sidebar box for writing goals either has to be very large (tall and wide), or very narrow in order to fit everything without having to scroll.

In either case, this leaves very little space to display things like the files (depending on where the writing goal is placed).

See this demo, which starts with my typical sidebar width:
![Obsidian_qT0sxAs6aY](https://github.com/lynchjames/obsidian-writing-goals/assets/33608083/ce84ba63-f821-41f7-95d5-20f336edd719)

Therefore, I think this needs to be improved, so writing goals don't take up unnecessary screen real estate.

**Comment by lynchjames** [comment]
Thanks for requesting. Are you looking for this to be scaled within your typical sidebar width with the circular progress svg as well as the summary text below or just the svg?

**Comment by FeralFlora** [comment]
> Are you looking for this to be scaled within your typical sidebar width with the circular progress svg as well as the summary text below or just the svg?

Yes, I think both could be optimized. The base size of the circle in relation to its container could probably be reduced a bit, and that would make a big difference. Below a certain threshold of sidebar width, the text below should probably be scaled dynamically too.

Another thing that could make a difference is if the circle scaling wasn't only width based, but also height based.

**Comment by lynchjames** [comment]
Thanks, could you share the computed width of the `view-content` div at your typical sidebar width?

**Comment by FeralFlora** [comment]
It's just about 360px

**Comment by lynchjames** [comment]
Scaling should be improved in release 0.5.4

**Comment by FeralFlora** [comment]
> Scaling should be improved in release 0.5.4

Thanks, it definitely is improved! However, I still think the circle svg is a bit too big. For now, I've moved it to the left sidebar, so I can keep my right sidebar as it was.

**Comment by lynchjames** [comment]
The size of the svg relative to the panel is controlled with padding. You could override this in a CSS snippet to tweak it further:

```css
.writing-goals {
    padding: 0 32px;
}
```

**Comment by FeralFlora** [comment]
> You could override this in a CSS snippet to tweak it further:

Thanks for the snippet!

**Comment by lynchjames** [comment]
FYI @FeralFlora I've moved CSS into the related svelte components in 07f4970 so you will need to update your snippet to this after the next release:

```css
.writing-goals {
    padding: 0 60px !important;
}
```
