### ISSUE TITLE
[FR] daily/repeating writing goals

### ISSUE THREAD

**Issue by danieltomasz** [lynchjames/obsidian-writing-goals#2]
I don't know if the way you getting  the number of words allows for that but if you store the number of words written per day (by simply tracking it on daily basis and saving in the plugin data per tracked file or folders) your plugin might be excellent way to track daily progress in the writing project (you might introduce additional optional property that might change yaml number of words to be interpreted as daily goal)

**Comment by danieltomasz** [comment]
My idea was not to store data about words in the yaml, more like to indicate the category that this word goal will repeat but maybe this isn't necessary; I checked Ulysses and still have some months of student license but I sticked to  Obsidian.

The writing goals are something that is really useful for me writing my  thesis,  thanks to it (even if not the repeated goals aren't there yet) I can see the progress, and day by day update word count; and the implementation is really beautiful, I like the rings 🙂

**Comment by lynchjames** [comment]
I see what you mean. So, daily goal and total goal progress could be presented something like this?

![Example-daily-goal-svg_resized](https://github.com/lynchjames/obsidian-writing-goals/assets/113271/6ab2b762-f056-4a33-847b-6ed03bf9021d)
