### ISSUE TITLE
[Feature/look] defult aligment of plugin chart and text  in the sidebar (centering or left/right)

### ISSUE THREAD

**Issue by danieltomasz** [lynchjames/obsidian-writing-goals#20]
The sidebar chart  in the Writing Goals plugin is currently left-aligned. One option could be to center align it by default instead.

![image](https://github.com/lynchjames/obsidian-writing-goals/assets/7980381/36bbb092-6013-4a5f-9d65-e0a22fdae42a)

Pros of center aligning:

- Looks nicer when the sidebar is wide
- Consistent with some other plugins/themes

Since this  probably can be changed by users via CSS (as the scalling),  https://github.com/lynchjames/obsidian-writing-goals/issues/17 , the default alignment could stay left for now. But it could  be mentioned in the README that users can center align the chart themselves if desired by adding custom CSS.

Pros of keeping left aligned:
- Still gives more control to users to modify via CSS
- Follows Obsidian default sidebar styles

Otherwise toggle in the settings might work (but it might overcrowd settings).

**Comment by lynchjames** [comment]
This is easy enough to make centred with CSS:

```css
.writing-goals-container {
    margin: auto;
}
```

I prefer this, so I'll add it as the default in the next release.

**Comment by lynchjames** [comment]
Default updated in 0.6.4
