### ISSUE TITLE
Compatibility with Novel Word Count :D

### ISSUE THREAD

**Issue by isaaclyman** [lynchjames/obsidian-writing-goals#22]
Hey, very cool plugin! It looks great and meets a real need. I'm excited for this to be available in the community plugin browser. Thanks also for the shout-out in the README, I hope it's okay that I'm [pointing people here](https://github.com/isaaclyman/novel-word-count-obsidian#shout-outs) from my plugin now as well.

A couple of thoughts:
- It appears this plugin works really well alongside Novel Word Count. However, there are some cases where our elements overlap in the File Explorer: if you choose the "Right-aligned" view option in NWC, or if you shrink the File Explorer leaf down so that there's not enough space for both. That's probably fine, honestly, but I expect a lot of people will be using our plugins together and I'd be happy to work with you on making them play nice. Maybe we could play with having the `.writing-goals-simple-container` element arrange itself via the parent flexbox context instead of being absolute-positioned? Let me know what you think.
- When I installed the plugin, my existing notes that had a `word-goal` property didn't get a progress circle until I either right-clicked and chose "Add writing goal" or updated their content. Not a big deal, but it would be cool to have those picked up automatically.
- It would be cool to be able to see the percentage completion of a note in the File Explorer along with the progress circle. Something like this? I imagine not everyone would want it, but I'm a sucker for details.
<img width="449" alt="Screenshot 2023-09-07 at 11 06 10 AM" src="https://github.com/lynchjames/obsidian-writing-goals/assets/9139369/7f1427ce-5b25-4f79-ae9b-e846289db7fe">

In any case, hats off to you for your work on this, excited to see where it goes from here.

**Comment by lynchjames** [comment]
Thanks for getting in touch and for referencing this plugin in your README 😄. I've submitted this plugin for review but have time to make some further improvements.

On your thoughts:

- Are you thinking of using a shared parent div with `display: flex` and other flex config to allow for either or both of the labels from our plugins to be displayed to the right of the `nav-folder-title-content` div? We could then both target that parent div with your label as 1st child and my label as 2nd child (when both plugins are enabled).
- That's a good point, the frontmatter is read to create new goals on file modification and frontmatter update events but this means existing notes with `word-count` in frontmatter won't generate goals initially. I'll have a look into a scan on plugin open to satisfy this use case.
- I had thought of that but had my concern was that the figure may be too small, particularly when there is also a daily goal in place. I'll have another look at it.

**Comment by isaaclyman** [comment]
Re: shared parent div. There's already a flex parent—`.nav-file-title` and `.nav-folder-title` both have `display: flex`. So if both our elements can arrange themselves in terms of that container, maybe they can coexist.

Re: percent display. It's true that the figure would be very small, maybe even unreadable if there were two progress circles. Maybe it would be better to have the percentage appear on hover? E.g. as a popover, a `title` attribute, or something along those lines. Then again, NWC displays the percentage already, so if they'll work side-by-side maybe it's a non-issue.

**Comment by lynchjames** [comment]
I've updated the CSS to remove the absolute positioning and it's looking ok along with the NWC label. Up to you if you want to keep it as an `::after` pseudo-element or move the NWC label into a div to have it to the left of the WG label.

![image](https://github.com/lynchjames/obsidian-writing-goals/assets/113271/f7848b6a-2975-46a8-a8a7-8a276d4ef04b)

**Comment by lynchjames** [comment]
Included in release [0.7.5](https://github.com/lynchjames/obsidian-writing-goals/releases/tag/0.7.5)

**Comment by isaaclyman** [comment]
Awesome, glad to see that worked.

- The progress circle is next to the file/folder name when NWC is turned off, instead of right-aligned. Is that intentional? You could set `flex: 1` on the `.nav-file-title-content` and `.nav-folder-title-content` if you want to keep the old positioning.
- Could you possibly set `order: 10` on your `.writing-goals-simple-container`? It doesn't have to be 10, I'm just thinking a high-ish number to indicate "hey, I prefer for this to appear at the end of the row," but then any other plugin(s) that use the same space can set their own order to decide whether to appear before or after the progress circle.

**Comment by lynchjames** [comment]
Thanks, I'm not very experienced with flexbox so this is really useful feedback! I've made both those changes, will go up in the next release.

**Comment by lynchjames** [comment]
Fixes in release 0.7.8

**Comment by isaaclyman** [comment]
Looks and works great! Thank you so much.
