### ISSUE TITLE
[bug] Word  count significantly  increases when adding a png file to the project folder

### ISSUE THREAD

**Issue by danieltomasz** [lynchjames/obsidian-writing-goals#24]
Steps to reproduce:

- Create a test folder and set a goal for this folder (in my case 20000 total and 1000 daily).
- Copy or move a png file from another folder to the test folder.
- Observe the word count of the project  - my case it added over 20k words (adding high qualtty png  with high resoltotion satisfied both daily and overal writting goal in my case).

Expected behavior:

The word count should not change when adding a png file.

Actual behavior:

The word count increases by 10000-20000 words depending on the size of the png file.

My temporary  workaround - I am having my figures in a separate folder outside the project;

Writing goals version: 0.7.6

**Comment by danieltomasz** [comment]
When fixing this issue other extension might be excluded as well like  jpeg , PDF doesnt seem to be counted

**Comment by lynchjames** [comment]
I'm assuming only markdown (`.md`) files should be included for word counts. If so, this is an easy fix.

**Comment by danieltomasz** [comment]
Not necessarily,  sometime I am using ".qmd" or ".rmd" or some other types of text files like ".txt" in Obsidian (but not in my writing project atm) , this is possible thankt to this 
https://github.com/MeepTech/obsidian-custom-file-extensions-plugin or similar plugins
 but 99 percent of people will use  only markdown so the solution you propose will be most general I think

I can think  of something like `wordcount: true` should be added  explicitly to yaml, of the  non-markdown file to override this  , otherwise all non `.md` should be exlcluded


But this could be thinked  of as a future extension,  your fix  atm solves the issue for 99% of users

**Comment by lynchjames** [comment]
Could also add a plugin setting to opt in other file extensions to an allow list and even a file-based action to exclude/include specific non-markdown files in word counts. Would you like to raise an FR for this?

**Comment by danieltomasz** [comment]
yes, I do it but I need to think a bit about what exactly this pull request might be.

I think it would be nice to have an option like `Excluded files` in Obsidian, where  user can use regex to filter out certain file extensions, subfolders, or markdown files. I could  a nice systematic way to exclude all file from  certain subfolders like `Drafts`  and even some markdown files without the need to add `wordcount: false` on every file.

Dual approach in the same settings  would be to define include list/whitelist to certain extension while all files with non-md extension are excluded by default.

**Comment by lynchjames** [comment]
Fixed in [0.7.7](https://github.com/lynchjames/obsidian-writing-goals/releases/tag/0.7.7)

**Comment by lynchjames** [comment]
Additional file type setting added in [0.8.1](https://github.com/lynchjames/obsidian-writing-goals/releases/tag/0.8.1)
