### ISSUE TITLE
[bug] when the folder with project is removed, the stats are still visible in the sidebar until reload of obsidian 

### ISSUE THREAD

**Issue by danieltomasz** [lynchjames/obsidian-writing-goals#25]
I created a test project for testing issue https://github.com/lynchjames/obsidian-writing-goals/issues/24

After filling the issue, I deleted the project in my file file manager,  but the stats were still visible. When I restarted the Obsidian the stats disseapered, but I got in place  of it an empty pane.

Expected behaviour:

After deleting the file or folder with the project the pane with project stats will be closed or automatically switched to other existing project.

**Comment by lynchjames** [comment]
Fixed in [0.7.7](https://github.com/lynchjames/obsidian-writing-goals/releases/tag/0.7.7)

**Comment by Medullitus** [comment]
> Fixed in [0.7.7](https://github.com/lynchjames/obsidian-writing-goals/releases/tag/0.7.7)

Helloo Are yyou here?
