### ISSUE TITLE
in-place update to 0.8.1 gives  blank goal stats graphs, manually reindexing is helping

### ISSUE THREAD

**Issue by danieltomasz** [lynchjames/obsidian-writing-goals#29]
After updating from version 0.8 to 0.8.1, I encountered a problem with the sidebar graph displaying a single goal and the tab showing all goals. Following the update, these graphs appeared blank, displaying no data (I had them open before update) .

Resolution Steps:
To resolve this issue, I attempted the following:

- Went to the settings menu.
- Initiated a reindexing process (I explicitly added the "md" option, although this may not be necessary).
- After reindexing, both the sidebar graph and the tab displaying all goals began displaying the expected data.

My thought:  You likely reindex when initially starting Obsidian or explicitly trigger a reindex, but it appears that reindexing doesn't automatically occur when you simply reload/reinstall  the plugin or isn't initiatlised somehow when moving from earlier version.

**Comment by lynchjames** [comment]
Full reload of goals and stats added on first plugin load in release 0.8.2

**Comment by danieltomasz** [comment]
@lynchjames  This behaviour repeated after updating to 9.0,  updating to 9.0 resulted in blank panes, reindexing helped
