### ISSUE TITLE
[FR] Option to ignore html comments when counting words

### ISSUE THREAD

**Issue by danieltomasz** [lynchjames/obsidian-writing-goals#3]
Would be great to have the possibility to set the option in settings to ignore words put in comments - either the one used by default by obsidian `%%` , or the standard html/multimarkdown `<-- -->`

**Comment by lynchjames** [comment]
I had just added code to ignore '%%' comments. I can also ignore '<-- -->' comments and include a setting.

**Comment by danieltomasz** [comment]
Thank you!I made a mistake, the multimarkdown syntax is '', with"!" included😅

**Comment by lynchjames** [comment]
Added in 0.4.1.

**Comment by danieltomasz** [comment]
thanks for adding it! I apologise I weren't enough specific in formulating my FR, when I added more specific example inline example, it weren't visible because github interpreted it as a comment, now I share example as raw markdown

Currently plugin only ignore inline comments, the content of block comment is stil counted.


```

This is an %%inline%% comment.

%%
This is a block comment.

Block comments can span multiple lines.
%%
```

Content of block comments spanning multiple lines is still counted.

HTML (multimarkdown) comments are used similarly

https://help.obsidian.md/Editing+and+formatting/Basic+formatting+syntax

```

<!---
All this should be 
commented out
-->

<!-- 
This too
-->

## Inline comments

How about commenting out <!--- just ---> a part of one line?
```

Thank for your hard work and adding this feature!

**Comment by danieltomasz** [comment]
I would expect 0 words here


```

<!-- my comment -->

%% My comment %%

%%

My comment

%%


<!-- 

My comment
-->
```

**Comment by danieltomasz** [comment]
I am personally most interested in stripping html comment, if you just using regex, try this, it should work for multiline html as well 
z()|()`

https://stackoverflow.com/a/53526783

**Comment by danieltomasz** [comment]
i tried to do a quick fork, but cannot install & compile because of obsidian api checksum fail (obsidian was updated today) but try this in line 36 in `obsidian-file.ts`
```
                meaningfulContent = this.removeCommentsRegex(new RegExp("<!--([\s\S]*?)-->", "gmi"), meaningfulContent);

```
I am not sure if this will work, I will investigate further tomorrow 😀

**Comment by lynchjames** [comment]
Thanks. I should've checked multiline. 

I'll have a look. There is a possibility that the markdown removing step added for #8 would exclude these anyway. I'll try that first.

**Comment by danieltomasz** [comment]
On the margin on this issue, but would you add your '.svelte-kit/tsconfig.json'to this repo? i have problem on building the plugin locally on my machine, I tried to add a default svelte config but it doesn't work - I don't have much experience with typescript🙂

**Comment by danieltomasz** [comment]
i quickly browsed the remove markdown library code, but it doesn't seem to do anything with comments (maybe it just remove tags <-- and %%, leaving text as it is)

**Comment by lynchjames** [comment]
Thanks for checking and for the Regex fix. Do you want to PR the change or shall I make it directly? If you raise a separate issue about tsconfig I can help to get you setup locally.

**Comment by danieltomasz** [comment]
I created a separate issue for the build problem, I can try with the PR
