### ISSUE TITLE
Characters are being counted as words

### ISSUE THREAD

**Issue by giseledute** [lynchjames/obsidian-writing-goals#30]
Characters are being counted as words.
Dash, question mark, exclamation, all count as words.
I write in Portuguese, and here we use a dash (—) separated from the words, so it counts as a word.
Example:

_—  Oi, tudo bem?_ (3 words)

![image](https://github.com/lynchjames/obsidian-writing-goals/assets/110442972/23199590-0f8d-4f8b-9cea-106ad6244b65)

I understand it's not an urgent “bug,” but in my language, it changes the count quite a bit.

**Comment by lynchjames** [comment]
Thanks for raising. Could you provide an example where question mark and exclamation mark are being counted as additional words? Are they being counted where there is a space between the word and the character?

**Comment by giseledute** [comment]
>  Could you provide an example where question mark and exclamation mark are being counted as additional words? Are they being counted where there is a space between the word and the character?

Yes! When they are separated by space, they are counted. So, the biggest problem is the dash :)

**Comment by lynchjames** [comment]
What about these examples?

_— Ei, você está bem? Qual seu nome? – pergunta o enfermeiro._ (10 words?)

_— Em que posso ajudá-la, Maria?_ (5 words?)

**Comment by giseledute** [comment]
> What about these examples?


It appears as 12 words and 6 words, instead of 10 & 5.

In fact, only the dash is counted as words in these examples.

**Comment by giseledute** [comment]
The “[Better Word Count](https://github.com/lukeleppan/better-word-count)” plugin makes the correct count. I use it in Obsidian because of this.

**Comment by lynchjames** [comment]
Should be fixed in [0.8.3](https://github.com/lynchjames/obsidian-writing-goals/releases/tag/0.8.3)

**Comment by giseledute** [comment]
It worked! Thank you!! <3
