### ISSUE TITLE
Interference with another popular plugin

### ISSUE THREAD

**Issue by Rhettica** [lynchjames/obsidian-writing-goals#31]
Hi,

I recently installed this and this it's exactly what I needed but when I turn writing goals on, all my text labels in the sidebar become right aligned leaving a massive amount of space between my icon and the note text. I've narrowed down the issue to a conflict between writing goals and the AnuPpuccin Plugin. Specifically the setting under Workspace > File Browser > Enable File Icons. Once this setting is turned off, writing goals works again but i'd rather keep it turned on since I like the icons. 

Could you please assist with fixing this?

Thank you.

<img width="285" alt="Screenshot 2023-09-12 at 6 34 57 pm" src="https://github.com/lynchjames/obsidian-writing-goals/assets/67592285/278eae10-63a7-407f-9543-28864783241f">
<img width="836" alt="SCR-20230912-qgdr" src="https://github.com/lynchjames/obsidian-writing-goals/assets/67592285/8456d24a-0b1d-4655-87f4-8d5b703e640b">

**Comment by lynchjames** [comment]
Thanks for raising this with the info and screenshot. I can recreate the issue and will look into a fix.

**Comment by lynchjames** [comment]
Should be fixed in [0.8.3](https://github.com/lynchjames/obsidian-writing-goals/releases/tag/0.8.3)

**Comment by lynchjames** [comment]
@Rhettica can you check if this is fixed in the latest release?
