### ISSUE TITLE
Text colour issue

### ISSUE THREAD

**Issue by Rhettica** [lynchjames/obsidian-writing-goals#32]
Hi,

I completed my writing goal today. The middle of the circle turned green when I did, which is great, but I believe my theme has made it so the text is almost invisible.

Would it be possible to add a text colour option for the words today counter please?

Thanks for the help.

<img width="285" alt="Screenshot 2023-09-14 at 6 51 16 pm" src="https://github.com/lynchjames/obsidian-writing-goals/assets/67592285/d976908e-c449-4931-896c-2f3bf70edcb3">

**Comment by lynchjames** [comment]
Additional custom colours are available in release [0.8.4](https://github.com/lynchjames/obsidian-writing-goals/releases/tag/0.8.4)

![custom-color-settings](https://github.com/lynchjames/obsidian-writing-goals/assets/113271/f9159326-c620-47b0-a847-ca3c685e3a3a)

**Comment by Rhettica** [comment]
Perfect! Thank you :)

**Comment by Medullitus** [comment]
> Additional custom colours are available in release [0.8.4](https://github.com/lynchjames/obsidian-writing-goals/releases/tag/0.8.4)
> 
> ![custom-color-settings](https://private-user-images.githubusercontent.com/113271/268111175-f9159326-c620-47b0-a847-ca3c685e3a3a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1MzIzOTcsIm5iZiI6MTcyMDUzMjA5NywicGF0aCI6Ii8xMTMyNzEvMjY4MTExMTc1LWY5MTU5MzI2LWM2MjAtNDdiMC1hODQ3LWNhM2M2ODVlM2EzYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwOVQxMzM0NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYmNiOWZkMDM3ZDYxMjQ3ZDM4YjNhZGRkYzIzMGU4YjcwMTZiZGRmYTJhYjQwYTVmMTg5NDA5ZjYwYTQwZTA1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-j37C-csSkxathwpCicgIm2g7aC7mFMTRjoZA_PaoEk)

Heyy. Are you here??
