### ISSUE TITLE
Regression - Ring backround doesn't adapt to light theme

### ISSUE THREAD

**Issue by danieltomasz** [lynchjames/obsidian-writing-goals#34]
With the latest change to set custom colors, the ring  and text no longer adjust to dark and light  version of the theme when they change (with the time of the day)
For example screenshots from 0.8.2
<img width="305" alt="image" src="https://github.com/lynchjames/obsidian-writing-goals/assets/7980381/22807909-04fa-4744-9920-74031c53c05a">
<img width="302" alt="image" src="https://github.com/lynchjames/obsidian-writing-goals/assets/7980381/2300b96e-a9fc-46ba-b5a7-d355c2a26622">

With the update to 0.8.4 the ring has dark background also in light mode
<img width="315" alt="image" src="https://github.com/lynchjames/obsidian-writing-goals/assets/7980381/58601086-5810-427a-b6de-0c0645db808b">

And the rings in the  file explorer  in light mode are dark (same color as in the dark mode)
<img width="320" alt="image" src="https://github.com/lynchjames/obsidian-writing-goals/assets/7980381/98592fe0-92df-4bca-af5d-17e7b56aa9e9">
<img width="312" alt="image" src="https://github.com/lynchjames/obsidian-writing-goals/assets/7980381/25d02ca4-e1d6-46c2-94a9-095e2977fe66">

Solution: add additional options to set default text and background  color per light/dark mode in settings)

(also it seems the word count  results changed between these two version, but I cannot pinpoint exactly what  changed, ifl the issue will be noticeable later I will create another issue)

**Comment by lynchjames** [comment]
For #32, I added custom colors which can be set in plugin settings. However, the defaults for these settings were specific colors. I should have set these as the [semantic color theme variables](https://docs.obsidian.md/Reference/CSS+variables/Foundations/Colors#Semantic+colors) (e.g. `--background-primary`).

If I change the defaults to be the appropriate variables, that should return the light/dark behaviour to what was available previously.

**Comment by lynchjames** [comment]
I've released a fix in [0.8.5](https://github.com/lynchjames/obsidian-writing-goals/releases/tag/0.8.5).

@danieltomasz If you toggle the "Enable custom colors" setting on and off, the colors should be set as the previous theme variables which will adapt to light and dark themes as well as community themes. This should be a one-time step.

**Comment by danieltomasz** [comment]
0.8.5 seems to fix my problem!

hower the dot  preview of colors are now black by default, while in  0.8.4  the  dots were in the colors that were  actually used, is this expected behaviour?
<img width="686" alt="image" src="https://github.com/lynchjames/obsidian-writing-goals/assets/7980381/5f07d764-ab95-4218-bfc5-7e643197e136">

**Comment by lynchjames** [comment]
Expected but not ideal so I've added another fix to set the color picker values to the defaults when you enable custom colors. Will go up in next release.

**Comment by lynchjames** [comment]
Fix in [0.9.0](https://github.com/lynchjames/obsidian-writing-goals/releases/tag/0.9.0)
