### ISSUE TITLE
[feature request] Can we have 'read time' goals as well 

### ISSUE THREAD

**Issue by championswimmer** [lynchjames/obsidian-writing-goals#39]
- settings to set reading speed 
	- even better if 200, 250, 300 all three speeds are there 
- based on reading speed, goal can be set for minutes of reading time 
- goals can be set either in words or in minutes
	- word goals, if present, will override minute goals

**Comment by lynchjames** [comment]
Thanks for the request. 

I think these requirements would be suited to a separate plugin. The Writing Goals plugin is focused on writing and word counts and I'd like to keep that focus.
