### ISSUE TITLE
[FR] Progress tracking

### ISSUE THREAD

**Issue by lucastucious** [lynchjames/obsidian-writing-goals#4]
Can we have a tracking of progress, like day/week/month stats ?

**Comment by lynchjames** [comment]
Thanks for the request. This is possible and a logical next step from #2 which I'm currently working on. Would you be looking for tracking of progress across both daily word goals (as described in #2) and the overall word goals?

**Comment by lynchjames** [comment]
Feature added in [0.6.0](https://github.com/lynchjames/obsidian-writing-goals/releases/tag/0.6.0)
