### ISSUE TITLE
I love it. 

### ISSUE THREAD

**Issue by Drakemoor** [lynchjames/obsidian-writing-goals#41]
I love this plug in. This is something I've long waited for. Unfortunately I can't find a way to install it. 
Can someone help, please?

**Comment by lynchjames** [comment]
That's great to hear!

As of today, the plugin is available in the Community Plugins, you can search there or here is a [direct link to the plugin in Obsidian](obsidian://show-plugin?id=writing-goals).

**Comment by Drakemoor** [comment]
Thank you! 🙇🏻‍♂️
