### ISSUE TITLE
Count Words in Codeblocks?  :) 

### ISSUE THREAD

**Issue by Bluemoondragon07** [lynchjames/obsidian-writing-goals#44]
Hi! I have tried to use writing plugins for Obsidian in the past, but I'd always keep going back to writing in Google Docs or Word, because they didn't seem to help me, really. Longform plugin, Writing plugin, none of them made things easier or motivated me to write. 
But then...
I got this plugin! And wow! I've been writing like crazy for once. This plugin is a huge motivator, and I really want to say: thank you for making this awesome plugin.

Also, I was wondering if you could add an option to include codeblocks in the wordcount. I use the Fountain plugin to write screenplays, so I use the codeblock to render the content. I thought it was a bug at first, but then I realized the Writing Goals plugin wasn't counting the text because it was in a codeblock. 

Right now I have to un-codeblock everything to see the word count, which is doable, but less convenient. An option to count words in codeblocks isn't essential, but it would be really nice. Please consider it, and thanks again for this plugin :)

**Comment by lynchjames** [comment]
Plugin setting to exclude/include code blocks added in [0.10.2](https://github.com/lynchjames/obsidian-writing-goals/releases/tag/0.10.2).
