### ISSUE TITLE
"failed to show goal for [filename]"

### ISSUE THREAD

**Issue by vagueposting** [lynchjames/obsidian-writing-goals#48]
I can still view the small goals in the file selector, but when I have to check the goals for my files then it just yields the error `failed to show goal for [filename]`

- I have a folder with a world goal and some unindexed files in it (.md files I converted to docx so I could verify word counts,) so the goals don't process _at all_.
- I open that folder in my system explorer, delete/relocate the unindexed files.
- I refresh the goals on Obsidian by using "Update writing goal" from the context menu OR by editing the frontmatter
- The goals (small circles) reappear on the Files tab on the sidebar.
- The big goal circles do _not_ reappear. It yields the error I mentioned.
- I have to uninstall and reinstall the plugin to get them to reappear

Am I doing something wrong or is this a bug?

**Comment by Medullitus** [comment]
Is the developer looking here?? I'm getting a 'FAILED TO SHOW GOAL' error toooooooo!!

**Comment by Medullitus** [comment]
https://github.com/lynchjames/obsidian-writing-goals/issues/57

**Comment by lynchjames** [comment]
This issue should be resolved by the performance improvements made in 0.10.1.
