### ISSUE TITLE
Plugin does not function anymore

### ISSUE THREAD

**Issue by Welstand** [lynchjames/obsidian-writing-goals#55]
The plugin does not function anymore, there is nothing to see and it does not track the word progress.

<img width="1969" alt="Bildschirmfoto 2024-03-06 um 09 34 40" src="https://github.com/lynchjames/obsidian-writing-goals/assets/71545203/244c5d33-3c62-403a-b035-aefd4c96ec44">

**Comment by Azmoinal** [comment]
I think that you have some files that are not .md in your vault.

If it is the case: could you try to explicitly put md, without commas, into the field “Additional file types” under Writing goals settings?

In my case it solved a similar issue with canvas a specific edtz file created by another plugin.

I'm not a developer but it could be a workaround, in the meantime that someone fixes the original issue.

**Comment by Welstand** [comment]
SAVED MY LIFE! I owe you a bunch @Azmoinal
