### ISSUE TITLE
Feature Suggestion: Store 'Goal progress' data in a note we can access instead of JSON

### ISSUE THREAD

**Issue by tobiasbuckell** [lynchjames/obsidian-writing-goals#58]
I deeply, deeply appreciate this plugin. I was wondering, is there an option to store the Goal Progress data somewhere besides the JSON plugin data area? I usually keep my writing logs in a spreadsheet so that I can pull charts from the data, and also so that if I need to adjust the writing logs (say I pasted something into a chapter, I don't want those words counted on my Goal Progress) I can. Right now my own data is hidden from me, and secondarily, JSON files seem to be hit up by the system frequently, so when the data gets messed up, I don't have backups of it like I do with my notes so I can revert the file or fix the data.

I also use the data to estimate how long it will take me to finish my draft (helpful for deadlines), so having access to the data would be huge.

**Comment by danieltomasz** [comment]
hi @tobiasbuckell I see your needs, but I think json structure is much nicer  than a plain note; but you can acces json data with various plugins like this one  https://github.com/farling42/obsidian-import-json

**Comment by tobiasbuckell** [comment]
Thank you for taking the time to get back to me, and being so understanding about what I was suggesting! 

Thank you for suggesting an existing solution! I’ll play with the JSON plugin to see if I can use it with the Obsidian graphs plugins to replicate what I need myself.

Best,

TB
www.TobiasBuckell.com

**Comment by lynchjames** [comment]
I have added a setting to allow for a csv export to be generated from the goal history data. This can be left enabled to continuously update the file or turned on and then off to generate a one off csv export. I can create a command for this as well if that is more useful.

![image](https://github.com/user-attachments/assets/0a41bac0-b171-4369-b5ec-7e3eb9755b3c)

**Comment by lynchjames** [comment]
Changes made in [0.10.1](https://github.com/lynchjames/obsidian-writing-goals/releases/tag/0.10.1).

**Comment by tobiasbuckell** [comment]
😍
Wow! That’s amazing. I know what I’ll be playing with this afternoon. I can then just pull up that data and play with Dataview, charts, or the sheets plugins.

James, you are amazing. Thank you so much for this.
