### ISSUE TITLE
[bug] Values <0 for daily-word-goal in ring in empty test note without setting general goal higher than daily goal

### ISSUE THREAD

**Issue by danieltomasz** [lynchjames/obsidian-writing-goals#6]
Creating empty file `test.md` and setting 100 words daily goal via right click on file in menu explorer shows -4 words today inside the ring.

When I add the general goal `word-goal` - 100 words (number I set equal to `daily-word-goal`) it shows -3 words today (incorrect number)

The file is empty apart of 2 lines of yaml about goals.

When I update overall `word-goal` number to be higher than `daily-word-goal` the behavior is fixed and daily goal ring shows me correctly 0 words today.

This could be replicated for any number in daily goal when  `daily-word-goal` is set or updated via right click menu on file when there is no `word-goal` set or `word-goal` is set below or equal  `daily-word-goal`.

Changing or creating the values directly in yaml doesn't lead to such error.

I can only guess that the plugin might initially counts words in yaml for daily goal, and then "forgets" about them when correctly interpreted yaml as yaml

**Comment by lynchjames** [comment]
Yes, your guess was right. The code was saving the history entry with zeros and then the entry was updated after the goal frontmatter was updated, resulting in the difference leading to the -4. 

I have a fix where the history item is stored before the frontmatter is updated when a goal is first added.
