### ISSUE TITLE
[question/bug] Header markers and word  counts

### ISSUE THREAD

**Issue by danieltomasz** [lynchjames/obsidian-writing-goals#8]
Should headers markers be counted as words?
Currently
```
## My title
```

gives me results of 3 words counted.

It could be potentially just be configured by user to by excluded in a user defined list of excluded words.

**Comment by lynchjames** [comment]
Header markdown syntax can be excluded. There is other markdown syntax (`- 1. --- `) that probably should be excluded. 

I would like to avoid processing the markdown to generate fully clean output as part of calculating word counts as that would likely hit performance but I could (1) apply a fixed list of markdown syntax to exclude and (2) a setting could be added for other customisable exclusions.

I will investigate (1) for this and then a separate issue could be raised for (2) if it's still needed.

**Comment by lynchjames** [comment]
I've got a fix using [remove-markdown](https://github.com/stiang/remove-markdown) which is using Regex and probably the way I would have gone anyway.
