### ISSUE TITLE
[FR] Exclude file from word count in folder

### ISSUE THREAD

**Issue by danieltomasz** [lynchjames/obsidian-writing-goals#9]
novel word count has yaml property

```
---
wordcount: false
---
```

for file in a folder to be excluded from counting words. Would be great to have a similar option (this one, or tag like`tags: exclude-from-word-count`, or new, similar but non-overlapping with other plugin solution) in the case of counting words in folders (often auxiliary files with other materials are stored together at the same level with the actual writing)

**Comment by lynchjames** [comment]
I'd prefer `wordcount`. I know Novel Word Count allows for that and the tag but I'd prefer just to go for this single option. 

Would this only apply to notes not contributing to the parent/grandparent etc. word count? So, a note could have this `wordcount: false` frontmatter property set and still have a goal and a daily goal set for that note?

**Comment by danieltomasz** [comment]
I don't have opinion in that matter, I was thinking in this case about examples like Index.md from long form or files like kanban boards to track progress et cetera

**Comment by lynchjames** [comment]
Added in 0.5.1.
